# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://vm-node-a.platform:8761/eureka/, http://vm-node-b.platform:8761/eureka/, http://vm-node-c.platform:8761/eureka/

# Spring Boot Actuator Configuration
management.endpoints.web.exposure.include=*

# Logging Levels
logging.level.lk.ijse.eca=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG