#server.port=8083
server.port=0

spring.cloud.gcp.project-id=project-83f3b203-b60d-481d-89d

#spring.cloud.gcp.credentials.location=classpath:project-83f3b203-b60d-481d-89d-eb3f681d0f1f.json

spring.cloud.gcp.credentials.encoded-key=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicHJvamVjdC04M2YzYjIwMy1iNjBkLTQ4MWQtODlkIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiODI5MzY5NjgyNjZmOGI3ZGNkZDUyNGY3MzdkNDJkNzkxOTBhNzdhMCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFETkpKTjRhb2pKZzhiRVxuMUQ5eDJ6Q2hFbzZKcHRWaXpMWEZrTnE3T1VhVTRLaW1wYjhPZXVXclBWUitkUituYk9sZG5qY2ZheDBLU1VKMVxucjRBSUhnMHIzcEZFTFEzMzc2L0NFN3MvaWw4R3V6R09MUEVSZDVjSGxtRjRCS3NlcXFjT2ZTQUFkNHFhdXhkSFxuQll0bXRlckt4MTBteE5rZTBjNGRjeDdVVVZsdXpIOXRXdmtZOThEaGdmb2ZjZ0VnYnpZeGlHUkJHS2pPdHBKZlxuck4wbUtPaWhGcTVsK0VJOUwrWmlNZ1JFMTh1M0J5V2ZHbXpJdVYxVy9XblB4cEpLRlhuejlXdHVvWmdVTDlKWlxuWHMrMjBldEZTejVmMGJwUFIwb0xFR0dseUxKOTdVaDVtSkRVNGhCc2ZoR1djUEtPSlFmaDZCeHBYcmZDY1NDUVxuYU5LeUxwV3RBZ01CQUFFQ2dnRUFJUFJmUEZqZzRINXF6L1BJdldHWXprZE0zcEFPZDNDclFyR2ljYkVoeFlqUlxuanZQUlhXSWd3d0YzTVZsZlhHWUNseWR6YzNpaGthVnpKN1NwdktRWE9aVG5nU3c3c2ppdTQxNklGZzBFZHZCYlxuWlp1U25sdTN4MkJCQ0NhMzFwVlRnT0JZNDdwUWFjcmtVbVJ4b0c1WTZYcGRYSDBDNUJDUUsrcnlhT2tvbE1PN1xualZJZnUzMGdQWjVkUFV2NURaZll0ZEk5UUJHYWNvSU1DRmZlTmM0Nnh3SVhxei9PcHgvYmJPNUNZSDVwL0NZYlxuTUhsY0ROMVYxdXFaRG9IQndWMVNDY0tyTVJuc3ZPUWxjOGVGdkYwdUdVenIrYzVoOS9Xd2Vic3RmajA4RTNlZVxuQUE4RXZYaU9SVS9jNm5OdTNURE9CSjRzUXhtTWkvM2VGNnNZaHErUUFRS0JnUURyUy9abkd0NXFNNDhnR1lMNVxucE5JWE45MVMvVk85Y1FOUGNtRjlTTWxIa3NVRDdXREZyVUpWeU0rUTNoZlhDdk9jUm14aTVTTzJaNlppNUFMRlxuZFVlNjM5dllBeHYyUlJwN0tzZ09aV0FnalZGQUVyUWpkUWRqcy9RVkpKMnhPa0N5UTl5MUtmSUcvRS9SbndtdVxuWUFYUHRLQ3FoV2ZpVjRTTUkrQ09qNHNWelFLQmdRRGZNV2FXVkl2VFRrWThLOVpkTzJXNHRiUzRIVWZHc2RKclxuNmhaTm9yWmY5TGVobGw0TjVybGVmU01OSEFnUTBRamFmOTB5K2srT1VpWmxQWmZVaVZsVjNGbW1aR1VBOWx0UVxuWUJLaUdWbHFkcnhrMlZCRS93WWROaVYxNTU1TjVFUGxBSUZoK2w4Rm1YZFdxNGRVNVB5MXRlNVVTb2k5S1U4blxudmdMUWlyV2ZZUUtCZ0NQUi82UDRvaTEyeGU0MEZBMWZPeUNQdjZEWHNmemdESW4ydHNLMDV2ZC9iNERHalhucVxuZzNPOXkyT1plL1dmMURCUlJFVFY3MWJnZHFNTlpTS2NWUndzNGpJRFh5bGhvY05vWXVaV0pva3VHbFZ2dzM2MlxuWFRhZmVhUVNXL05VRSs5UGgzVUkrckIzanNzeHMrNlk3YW1PTFB0b3JjVDJYOVpaeStESUYzdHRBb0dBQkdkSVxuRzkwdEtRMFpTNlNkeFJjZjZhWUVHOEhRSWJadWJWeWY5Z1lvelBuYUNhRWExL0ZlWk9QWkpqQVFaS3lMSFN4NlxubzcvV2cvdFE4SnhuZTNUK1F6aG11R2F3cTNVdzFnUWZPZjJBQ3g2dWx0ckd2Nlc4YkNVZVZoWXN4R0tsaUVZYlxuUjJDV01Wa1d4cW41c0k0WUFrbkZtdm9oZW9Idkl0eVgxNTkwOStFQ2dZRUF5eGUwN0ZZdEs5YUxIWWc0VnBiVVxuZERpeWpFZnZMQW40VzhqWVRiNkdPUE9MWkdzYnVJcGcwSE5MM3dFd05YQWFmTGRicm9jaDZ1ams2c2lVOVcrZ1xuVGxmS3FHOXlHNHA3anIxVjFGeVYzNWo5b09ZQkxVVU4zUVovSWhnT1dhajBCWnZwM3FmMVVtSjJqZkhCb29Rb1xuUmZqV1hGNjNRaE5HQ3ZVbWF0cHpiRU09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAic2EtamRtLWV4cG9AcHJvamVjdC04M2YzYjIwMy1iNjBkLTQ4MWQtODlkLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwMDU3MzgyNTYwNTU4NzgwNTUxNiIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvc2EtamRtLWV4cG8lNDBwcm9qZWN0LTgzZjNiMjAzLWI2MGQtNDgxZC04OWQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K


app.gcp.bucket=jdm-expo-image-storage

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

#eureka.instance.prefer-ip-address=true

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}


# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://vm-node-a.platform:8761/eureka/, http://vm-node-b.platform:8761/eureka/, http://vm-node-c.platform:8761/eureka/

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Spring Boot Actuator Configuration
management.endpoints.web.exposure.include=*

# Logging Levels
logging.level.lk.ijse.eca=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

