#server.port=8083
server.port=0

spring.cloud.gcp.project-id=project-83f3b203-b60d-481d-89d

#spring.cloud.gcp.credentials.location=classpath:project-83f3b203-b60d-481d-89d-eb3f681d0f1f.json

app.gcp.bucket=jdm-expo-image-storage

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

#eureka.instance.prefer-ip-address=true

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}


# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://vm-node-a.platform:8761/eureka/, http://vm-node-b.platform:8761/eureka/, http://vm-node-c.platform:8761/eureka/

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Spring Boot Actuator Configuration
management.endpoints.web.exposure.include=*

# Logging Levels
logging.level.lk.ijse.eca=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

