# Eureka Server Configuration served centrally
server.port=8761





#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

# Actuator Exposure
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://vm-node-a.platform:8761/eureka/, http://vm-node-b.platform:8761/eureka/, http://vm-node-c.platform:8761/eureka/

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Spring Boot Actuator Configuration
management.endpoints.web.exposure.include=*

# Logging Levels
logging.level.lk.ijse.eca=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
