# Server Port
#server.port=8082

server.port=0

# MongoDB Connection
spring.mongodb.uri=mongodb://root:KwwTGQI9jHoXP2UQx9iwOmNBdz5N8fVP4T10pF_oNg_lIC6f@961724d2-9c0d-4bea-8eee-54b8fca5fe6e.asia-south1.firestore.goog:443/jdm-expo-mongo-db?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false
# mongodb://localhost:27017/jdm_order_db

# Eureka Discovery Client Configuration
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true



# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}