spring.cloud.gcp.project-id=project-83f3b203-b60d-481d-89d

spring.cloud.gcp.credentials.location=classpath:project-83f3b203-b60d-481d-89d-eb3f681d0f1f.json

app.gcp.bucket=jdm-expo-image-storage

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

eureka.instance.prefer-ip-address=true

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

