# Server Port
server.port=8082

# MongoDB Connection
spring.mongodb.uri=mongodb://localhost:27017/jdm_order_db
# mongodb://localhost:27017/jdm_order_db

# Eureka Discovery Client Configuration
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true



# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always