# Eureka Server Configuration served centrally
server.port=8761





#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

# Actuator Exposure
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always