# Server Port
server.port=8080

# Connect Gateway to Eureka Discovery Server
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/





# Enable Automatic Routing based on Eureka Registered Microservices
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=jdm-expo-vehicle-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://JDM-EXPO-VEHICLE-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/vehicles/**
spring.cloud.gateway.server.webflux.routes[1].id=jdm-expo-order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://JDM-EXPO-ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/orders/**
spring.cloud.gateway.server.webflux.routes[2].id=jdm-expo-media-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://JDM-EXPO-MEDIA-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/media/**

# Actuator & Gateway Route Exposure
management.endpoints.web.exposure.include=health,info,metrics,gateway
management.endpoint.health.show-details=always